name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: Mefika
      fonts: 
        - asset: lib/assets/fonts/mefika-font/Mefika.ttf

  assets:
    - lib/assets/images/

  uses-material-design: true
